[project]
name = "parking_monitor"
version = "2.1.0"
description = "parking monitor demo using Raspberry Pi AI Camera"
authors = [{name="Sony Semiconductor Solutions Corp"}]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11,<3.14"

dependencies = [
    "configurator",
    "modlib==1.3.1",
]

[tool.uv.sources]
configurator = { path = "../../tools/configurator" }
